### PR TITLE
Lab 2

### PR DESCRIPTION
**Pull request by polinasevko**

### CODE REVIEW

**Comment by nastik1811** [comment]
I think `<table>` is more appropriate tag for this kind of information.
image

**Comment by nastik1811** [comment]
Also I don't see authorisation forms and the difference between three last pages is not clear.

**Comment by nastik1811** [comment]
Anyway, I can approve it now, assuming that you will consider the comments in the further milestone. But "7" is the highest mark I can offer you now, since the UI is quite poor (too few elements). Let me know if you're agree with this mark

**Comment by polinasevko** [comment]
Added footer and nav tags. 3 last pages are used in different stages, it will be clear in finished application. I would like to raise the mark to 8.

**Review by nastik1811 — APPROVED** [review]
Okay, let's leave it as it is for now (perhaps, you need to add some features in the further steps). Your mark is `8`

**Pull request merged**
